### ISSUE TITLE
Serving with --neuron.no_set_weights calls metagraph.sync every minute or two

### ISSUE THREAD

**Issue by RD4Fun** [camfairchild/bittensor#1019]
The server updates the console with the current weights every minute or so
Unnecessary calls to metagraph.sync() which could affect performance of the server and whole network

Only occurs if argument --neuron.no_set_weights is true 

https://github.com/opentensor/bittensor/blob/661c73dd4c32a5c551b49a509708c254a44297a2/bittensor/_neuron/text/core_server/run.py#L436

![image](https://user-images.githubusercontent.com/119458939/204955526-37e80a5b-4db1-4636-a804-a3e22dce95e9.png)

**Comment by camfairchild** [comment]
Merged into nobunaga

**Comment by eduardogr** [comment]
Just commenting that this will be closed when merging the staging branch `nobunaga` into master for the next release: 3.6.0
