### ISSUE TITLE
Error when using btcli overview on Finney (unexpected keyword argument 'hotkey')

### ISSUE THREAD

**Issue by Inquinim** [camfairchild/bittensor#1045]
I'm testing out the add_network_uids branch. Tried to run btcli overview but encountered the following error:
TypeError: get_netuids_for_hotkey() got an unexpected keyword argument 'hotkey'

This line errors: 
https://github.com/opentensor/bittensor/blob/13bce51ec1539d51368096b5c3d51f97a6460ab6/bittensor/_cli/cli_impl.py#L810

Looks like it might need to be ss58_hotkey like here (just a guess): https://github.com/opentensor/bittensor/blob/13bce51ec1539d51368096b5c3d51f97a6460ab6/bittensor/_cli/cli_impl.py#L277

**Comment by unconst** [comment]
Hi @Inquinim: FYI, finney is in development and likely should not be used until released

**Comment by Inquinim** [comment]
> 

Yep no worries, I was doing some testing pre-release and ran into those bugs so thought I'd mention them.
