### ISSUE TITLE
Error running btcli inspect on Finney (no attribute 'get_stake')

### ISSUE THREAD

**Issue by Inquinim** [camfairchild/bittensor#1046]
Tried running btcli inspect from the add_network_uids branch.

Received this error; AttributeError: 'Subtensor' object has no attribute 'get_stake'

For this line:
https://github.com/opentensor/bittensor/blob/13bce51ec1539d51368096b5c3d51f97a6460ab6/bittensor/_cli/cli_impl.py#L270

**Comment by unconst** [comment]
Same as other comment. :)
