### ISSUE TITLE
Able to create a hot key without an associated cold key

### ISSUE THREAD

**Issue by RD4Fun** [camfairchild/bittensor#1047]
**Describe the bug**
btcli new_hotkey using a coldwallet name that does not exist completes and creates a hotkey that is registerable and can be used to mine but does not have a cold key for the TAO

**To Reproduce**
$ btcli new_hotkey
Enter wallet name (default): jj
Enter hotkey name (default): t01
$  btcli list

then create/regen the cold key name jj

**Expected behavior**
Reject the new_hotkey command saying that the cold key name does not exist

**Screenshots**
attached
![btcli new_hotkey](https://user-images.githubusercontent.com/119458939/211176514-3882f1b3-db70-4f0f-9fa7-843d4f15dddb.png)

**Environment:**
runpod opentensorfdn/bittensor:3.6.1-cubit1.1.2

**Comment by camfairchild** [comment]
>**Expected behavior**
Reject the new_hotkey command saying that the cold key name does not exist

I'm not sure this is the expected behaviour. You can successfully run `btcli new_coldkey --wallet.name jj` after the `btcli regen_hotkey --wallet.name jj` command.

I'll close today if I don't hear back. Feel free to re-open after then.

**Comment by RD4Fun** [comment]
thanks please close - my confusion regarding the key creation and key registration processes
hot key creation does not require any cold key 
The registration or any other process that requires a cold key will fail (coldkeypub.txt not found)
Key registration does require a cold key/hotkey pair - only registered keys can stake / unstake and earn TAO
