### ISSUE TITLE
Connection refused when using external endpoint with Finney

### ISSUE THREAD

**Issue by Inquinim** [camfairchild/bittensor#1051]
https://github.com/opentensor/bittensor/blob/017952f7c28f4370bc6d1c9add0c4d728072218e/bittensor/_subtensor/__init__.py#L111

I spent some time debugging and narrowed the error down to this line. (Nothing executes after it.) I can confirm that the chain endpoint is showing up in the config correctly but we error out here.

Command used to start the miner:
btcli run --wallet.name fin --wallet.hotkey f1 --subtensor.network local --subtensor.chain_endpoint IP:9945

Running a Finney miner on the VPS also running paratensor locally doesn't work either.

Stacktrace:
[stacktrace.txt](https://github.com/opentensor/bittensor/files/10387998/stacktrace.txt)

**Comment by shibshib** [comment]
Turned out the docker image needed a fix as well as the bittensor finney branch. Please pull the latest docker image and bittensor branch and retry, it should work from here on out.
