### ISSUE TITLE
Prompted to select network on Finney even when --subtensor.network finney argument is passed

### ISSUE THREAD

**Issue by Inquinim** [camfairchild/bittensor#1052]
https://github.com/opentensor/bittensor/blob/017952f7c28f4370bc6d1c9add0c4d728072218e/bittensor/_cli/commands/run.py#L87

When using 'btcli run' it prompts me to select the network even though I pass in the --subtensor.network finney argument.

Changing the referenced line above to:
if **not** config.subtensor.get('network') == bittensor.defaults.subtensor.network and not config.no_prompt:

Resolved the issue.

**Comment by camfairchild** [comment]
Fixed in #1182
