### ISSUE TITLE
Add the possibility to write end to end tests that allows us to test pip package executions

### ISSUE THREAD

**Issue by eduardogr** [camfairchild/bittensor#1066]
**Is your feature request related to a problem?**
Maybe unit tests and integration tests cover a usecase but nothing is covering the pip package execution

**Describe the solution you'd like**
- Adding a directory `tests/e2e_tests`
- Adding a file for each **btcli** command. e.g.:
    -  `tests/e2e_tests/help.py`
    -  `tests/e2e_tests/overview.py`
    -  `tests/e2e_tests/list.py`
    - ..., etc
- Adding job in `circleci/config.yml` to execute end to end tests.
- Adding workflow in `circleci/config.yml` to trigger the end to end execution for every branch  

**Describe alternatives you've considered**
1. Creating the pip package locally and execute it as a OS program from python.
1. Execute the same Python entrypoint that the pip package executes.

**Additional context**
We have merge some branch that had passing tests but some **btcli** comands were failing

**Comment by robtaylor** [comment]
Is this a current concern? I'd be happy to put some effort into reproducible python Pascal aging & test.

**Comment by eduardogr** [comment]
> Is this a current concern? I'd be happy to put some effort into reproducible python Pascal aging & test.

I think we do not have tests for the cli itself, so, please, feel yourself free to proceed in the way you think you can add value to the project. It's much appreciated 🙏🏽
