### ISSUE TITLE
Update Protobuf and Torch

### ISSUE THREAD

**Issue by 21bloc** [camfairchild/bittensor#1129]
I recommend updating your protobuf to a newer version and torch from 1.12 to 1.13, This creates alot of dependency errors with newer libraries. Cheers fam

**Comment by camfairchild** [comment]
> torch from 1.12 to 1.13    

We've updated `torch` to `1.13.1` 
Which version of `protobuf` have you found is stable?

**Comment by 21bloc** [comment]
4.20 is the current i believe, or something like that, I would also update
the substrate-interface to 1.6.

**Comment by ifrit98** [comment]
No mo protobuf!

**Comment by 21bloc** [comment]
I still see grpc being used, is it in a separate branch

**Comment by camfairchild** [comment]
> I still see grpc being used, is it in a separate branch

It should be in the `revolution` branch
