### ISSUE TITLE
Cannot see or access my staked Tao

### ISSUE THREAD

**Issue by willsmore** [camfairchild/bittensor#1303]
Hello there
I staked 6 Tao for the first time before adding another 3 Tao. The 6 was showing up when I checked the chainstate but then when I added the 3 more, it did show up after I signed the transaction. 
I don't know where to access the history of these transactions but now have 0 showing staking and also only my remaining 4.39 on the account. 
My account is 5EyWnQaZtFwpserDYnwSYteNid2Lp2rBfqa3j2paWH6kvFtk
I would really appreciate help with this.

**Comment by willsmore** [comment]
I will try other ways to get help with this.

**Comment by Inquinim** [comment]
Hi Will, I recommend asking for help in the Discord server as you will get help a lot faster.
