### ISSUE TITLE
Import torch statement missing from Cerebras' neuron.py

### ISSUE THREAD

**Issue by iFimbrethil** [camfairchild/bittensor#1329]
**Describe the bug**
And import torch statement is missing from neuron.py in the cerebras directory causing the script to error when run. Adding import torch allowed the script to run properly

**To Reproduce**
pm2 start ~/.bittensor/bittensor/neurons/text/prompting/miners/cerebras/neuron.py

Error: No Module named torch

**Comment by arain60gb** [comment]
@iFimbrethil 
use import torch in neuron.py

**Comment by camfairchild** [comment]
Closing as fixed in #1460
