### ISSUE TITLE
Reimplement `to_wandb()` for dendrite and metagraph on `text_prompting`.

### ISSUE THREAD

**Issue by ifrit98** [camfairchild/bittensor#1332]
See:
https://github.com/opentensor/bittensor/blob/master/bittensor/_dendrite/dendrite_impl.py#L1028

and

https://github.com/opentensor/bittensor/blob/master/bittensor/_metagraph/metagraph_impl.py#L406

**Comment by ifrit98** [comment]
This is a stub for later and to spark discussion.  Figure this may be useful for continual monitoring and analysis, yes @steffencruz ?

**Comment by steffencruz** [comment]
ohfosho!

**Comment by ifrit98** [comment]
Outdated.
