### ISSUE TITLE
Documentation paths for neuron.py are incorrect.

### ISSUE THREAD

**Issue by icsy7867** [camfairchild/bittensor#1404]
**Describe the bug**
Path for neuron.py (Possibly others) are incorrect.
**To Reproduce**
Follow the documentation.

**Expected behavior**
It should work.

**Screenshots**

**Environment:**
N/A

**Additional context**
Following:
https://bittensor.com/documentation/mining/mining

The first command after the git clone is:
```
python3 -m pip install -r bittensor/neurons/text_prompting/miners/GPT4ALL/requirements.txt
```
**However this does not seem valid**.  It is now:
bittensor/neurons/text/prompting/miners/gpt4all/neuron.py
https://github.com/opentensor/bittensor/blob/master/neurons/text/prompting/miners/gpt4all/neuron.py

**Comment by eloenwa** [comment]
Fixed
