### ISSUE TITLE
How to check registered

### ISSUE THREAD

**Issue by thapld** [camfairchild/bittensor#1479]
### Describe the bug

I register to finney and netuid 1. But I cannot know when it success or not. Which btcli command can do that

### To Reproduce

btcli register --cuda

### Expected behavior

Check register status and show endpoint if success

### Environment

Linux, v5.3.3

**Comment by camfairchild** [comment]
Hello! You should use `btcli inspect --wallet.name <coldkey_name> --wallet.hotkey <hotkey_name>`
