### ISSUE TITLE
Erroneous `pkg_resources` deprecation warning on `btcli` commands

### ISSUE THREAD

**Issue by satoshitty** [camfairchild/bittensor#1487]
### Describe the bug

Attempting to run btcli commands can sometimes result in a deprecation warning for `pkg_resources` but is actually erroneous.

The problem is with pip when installing bittensor from source, which uses an incorrect codepath for running editable installs.

See: https://github.com/pypa/setuptools/issues/3981#issuecomment-1636033147

### To Reproduce

E.g. if you install bittensor like so:
```bash
cd bittensor
python -m pip install -e .
```

You'll get:
```bash
$btcli overview
~/bin/btcli:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('bittensor==6.0.0')
Enter wallet name (default): 
```

### Expected behavior

There should be no deprecation warning.

### Environment

Linux

**Comment by ifrit98** [comment]
This should solve it:

When installing bittensor with editable installs use: `--use-pep517`. 

e.g. when inside the main repo directory `bittensor`:

`python -m pip install -e . --use-pep517`
