### ISSUE TITLE
btcli walletfaucet fails in 6.0.1

### ISSUE THREAD

**Issue by mekaneeky** [camfairchild/bittensor#1546]
### Describe the bug

Attempting to follow the instructions for creating a staging subnet using the template at https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md

On running
btcli wallet faucet --wallet.name owner --subtensor.chain_endpoint ws://127.0.0.1:9946 

I receive the following error and traceback 
│ /home/ali/.local/bin/btcli:9 in <module>                                                         │
│                                                                                                  │
│    6                                                                                             │
│    7 if __name__ == '__main__':                                                                  │
│    8 │   args = sys.argv[1:]                                                                     │
│ ❱  9 │   bittensor.cli(args=args).run()                                                          │
│   10                                                                                             │
│   11 # The MIT License (MIT)                                                                     │
│   12 # Copyright © 2021 Yuma Rao                                                                 │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/bittensor/cli.py:271 in run                        │
│                                                                                                  │
│   268 │   │   │   command_data = COMMANDS[command]                                               │
│   269 │   │   │                                                                                  │
│   270 │   │   │   if isinstance(command_data, dict):                                             │
│ ❱ 271 │   │   │   │   command_data["commands"][self.config["subcommand"]].run(self)              │
│   272 │   │   │   else:                                                                          │
│   273 │   │   │   │   command_data.run(self)                                                     │
│   274 │   │   else:                                                                              │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/bittensor/commands/register.py:248 in run          │
│                                                                                                  │
│   245 │   │   r"""Register neuron."""                                                            │
│   246 │   │   wallet = bittensor.wallet(config=cli.config)                                       │
│   247 │   │   subtensor = bittensor.subtensor(config=cli.config)                                 │
│ ❱ 248 │   │   subtensor.run_faucet(                                                              │
│   249 │   │   │   wallet=wallet,                                                                 │
│   250 │   │   │   prompt=not cli.config.no_prompt,                                               │
│   251 │   │   │   TPB=cli.config.register.cuda.get("TPB", None),                                 │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/bittensor/subtensor.py:478 in run_faucet           │
│                                                                                                  │
│    475 │   │   log_verbose: bool = False,                                                        │
│    476 │   ) -> bool:                                                                            │
│    477 │   │   """Registers the wallet to chain."""                                              │
│ ❱  478 │   │   return run_faucet_extrinsic(                                                      │
│    479 │   │   │   subtensor=self,                                                               │
│    480 │   │   │   wallet=wallet,                                                                │
│    481 │   │   │   wait_for_inclusion=wait_for_inclusion,                                        │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/bittensor/extrinsics/registration.py:420 in        │
│ run_faucet_extrinsic                                                                             │
│                                                                                                  │
│   417 │   │   │   │   │   │   update_interval=update_interval,                                   │
│   418 │   │   │   │   │   │   log_verbose=log_verbose,                                           │
│   419 │   │   │   │   │   )                                                                      │
│ ❱ 420 │   │   │   call = subtensor.substrate.compose_call(                                       │
│   421 │   │   │   │   call_module="SubtensorModule",                                             │
│   422 │   │   │   │   call_function="faucet",                                                    │
│   423 │   │   │   │   call_params={                                                              │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/substrateinterface/base.py:1714 in compose_call    │
│                                                                                                  │
│   1711 │   │   │   type_string='Call', metadata=self.metadata                                    │
│   1712 │   │   )                                                                                 │
│   1713 │   │                                                                                     │
│ ❱ 1714 │   │   call.encode({                                                                     │
│   1715 │   │   │   'call_module': call_module,                                                   │
│   1716 │   │   │   'call_function': call_function,                                               │
│   1717 │   │   │   'call_args': call_params                                                      │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/scalecodec/base.py:771 in encode                   │
│                                                                                                  │
│   768 │   │   │   self.value_serialized = value                                                  │
│   769 │   │   │   self.decoded = True                                                            │
│   770 │   │                                                                                      │
│ ❱ 771 │   │   self.data = self.process_encode(self.value_serialized)                             │
│   772 │   │                                                                                      │
│   773 │   │   if self.value_object is None:                                                      │
│   774 │   │   │   self.value_object = self.value_serialized                                      │
│                                                                                                  │
│ /home/ali/.local/lib/python3.10/site-packages/scalecodec/types.py:1572 in process_encode         │
│                                                                                                  │
│   1569 │   │   │   self.call_function = call_obj.scale_info_type['def'][1].get_variant_by_name(  │
│   1570 │   │   │                                                                                 │
│   1571 │   │   │   if not self.call_function:                                                    │
│ ❱ 1572 │   │   │   │   raise ValueError(f"Call function '{value['call_module']}.{value['call_fu  │
│   1573 │   │   │                                                                                 │
│   1574 │   │   │   self.value_object['call_function'] = self.call_function                       │
│   1575                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Call function 'SubtensorModule.faucet' not found

### To Reproduce

1. Go to https://github.com/opentensor/bittensor-subnet-template/blob/main/docs/running_on_staging.md
2. Run all steps until reaching btcli wallet faucet --wallet.name owner --subtensor.chain_endpoint ws://127.0.0.1:9946 

### Expected behavior

Faucet should instead successfully deposit to the wallet in question

### Environment

Ubuntu 22.04.3 LTS Python 3.10.2

**Comment by niljub** [comment]
Hello everyone,

 is anyone already working on this issue?

If not, I would like to tackle it.

**Comment by ifrit98** [comment]
The faucet is intentionally turned off due to users spamming it. 

If you need test tao, please mine it or ask around the community for extra they may have.

**Comment by hamletwasntfat** [comment]
what about local testnet? Is it impossible in newer bittensor cli versions?
