### ISSUE TITLE
Switch dead explorer links to x.taostats.io

### ISSUE THREAD

**Issue by mogmachine** [camfairchild/bittensor#1583]
### Describe the bug

I cannot create a branch to do this as i don't have permissions ,so rather than submet file changes directly.

bittensor/__init__.py :: 107-111  - replace with

```
__network_explorer_map__ = {
    "local": "https://x.taostats.io",
    "endpoint": "https://x.taostats.io",
    "finney": "https://x.taostats.io",
}
```

Then

```
bittensor/utlis/__init__.py :: 167-173  - replace with

    if explorer_root_url is not None:
        # We are on a known network.
        explorer_url = "{root_url}/search?query={block_hash}".format(
            root_url=explorer_root_url, block_hash=block_hash
        )

    return explorer_url
```

### To Reproduce

This will no longer take you to a 502 bad gateway page because old explorer is dead.

### Expected behavior

This will take you to taostats, search the block hash and redirect you to the block page directly, eg: https://x.taostats.io/block/1732715

### Environment

bt 6.2.0

**Comment by ifrit98** [comment]
This seems to not be dead:

<img width="1705" alt="image" src="https://github.com/opentensor/bittensor/assets/31426574/e6c9a036-9506-4517-af2b-bfa043857edb">

Closing.

**Comment by ifrit98** [comment]
Resurrecting this. Seems there's an issue with the explorer querying specific blocks.

**Comment by ifrit98** [comment]
https://github.com/opentensor/bittensor/pull/1607

This is being addressed here.
