### ISSUE TITLE
How to config bittensor prune ?

### ISSUE THREAD

**Issue by bobbychen** [camfairchild/bittensor#1605]
### Describe the bug

Can not found bittensor prune config when running a node.

### To Reproduce

Running a bittensor node

### Expected behavior

Prune block automatically.

### Environment

Linux

**Comment by ifrit98** [comment]
Can you give more details? This is vague and unclear. Please provide any information relevant, such as code snippets, outputs, and/or tracebacks you see

**Comment by bobbychen** [comment]
Sorry for the unclear description. My question is how to config bittensor prune strategy.
Because my running fullnode just keep about 200 blocks. I want keep more blocks on node.

**Comment by camfairchild** [comment]
this is a better issue for https://github.com/opentensor/subtensor

And for reference, you can try adding (adjusting) the `--pruning` flag on your subtensor node
