### ISSUE TITLE
btcli shows burn instead of recycle

### ISSUE THREAD

**Issue by fahimahmedx** [camfairchild/bittensor#1619]
### Describe the bug

<img width="451" alt="image" src="https://github.com/opentensor/bittensor/assets/68152521/db645e58-5beb-46ca-9495-3946b7093bf3">

The `BURN` column is misleading and actually refers to the `RECYCLE` cost.

### To Reproduce

1. run `btcli s list`

### Expected behavior

The burn column should be renamed as recycle.

### Environment

Ubuntu 22.04

**Comment by ifrit98** [comment]
Getting included in next release.
