### ISSUE TITLE
btcli feature request

### ISSUE THREAD

**Issue by zikziktao** [camfairchild/bittensor#1624]
### Is your feature request related to a problem? Please describe.

I am not able to remove all staked $tao from all my hotkeys at once, that are connected to my coldkey. It is very cumbersome to have to do each one at a time, especially for those who have a lot of hotkeys.

### Describe the solution you'd like

 I would like a feature that can unstake all $tao from all my hotkeys at once, that are connected to my coldkey. something like "btcli stake remove-all"

**Comment by devderatta** [comment]
btcli st remove --all_hotkeys
![image](https://github.com/opentensor/bittensor/assets/152772873/17025ed8-4e85-4843-bba1-472967cd13a9)

**Comment by zikziktao** [comment]
thanks!
