### ISSUE TITLE
Set Validator Take

### ISSUE THREAD

**Issue by frankrizz07** [camfairchild/bittensor#1644]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I, as a validator, need to send 'x' tao to different wallets that are different take amounts. The updated btcli documentation shows commands that would allow a static validator 'take' per wallet.  This would make my life so much easier!

### Describe the solution you'd like

please push out the documented btcli commands that are published on the docs.bittensor.com website.
btcli root set_delegate_take --wallet.name my_wallet --wallet.hotkey my_hotkey --take 0.1

**Comment by frankrizz07** [comment]
Spoke with Const about this today and he said that he was going to mention it to you guys but I could also post his here. Figured both would be best. Thank you. -Rizzo

**Comment by ifrit98** [comment]
I'm not sure what you mean by this. Do you want to send different amounts of Tao to different wallets at the same time? 

Validator `take` is the percent of tao that is taken as a "fee" for delegations. Default is `18%`

**Comment by frankrizz07** [comment]
Yes, I as a validator, i would like to set a different 'take' per wallet. It looks like the updated documentation on the website lists the btcli commands to do this. But they are not enabled yet as I cannot find the commands.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ifrit98** [comment]
This is not an allowed feature and may be reintroduced in the future but must be examined carefully.
