### ISSUE TITLE
Bittensor 6.6.0: btcli st show returns "object is not iterable" error

### ISSUE THREAD

**Issue by Jackalgirl** [camfairchild/bittensor#1649]
### Describe the bug

Although btcli st -h lists "show" as an applicable command, typing 'btcli st show' returns "TypeError: 'subtensor' object is not iterable".

### To Reproduce

1) Verify current version is 6.6.0
2) Type 'btcli st show --wallet.name (name)' or just "btcli st show" and follow the prompts.

### Expected behavior

The command should "...List all stake accounts for wallet" as per the help command.

### Screenshots

<img width="715" alt="btcli-st-show_01" src="https://github.com/opentensor/bittensor/assets/88459050/ad3b4697-8c0b-4978-82f3-6a955ea68c9f">
<img width="715" alt="btcli-st-show_02" src="https://github.com/opentensor/bittensor/assets/88459050/95ecc296-4302-4232-8f94-6edfa5941492">

### Environment

MacOS, Bittensor 6.6.0

### Additional context

First reported in the Discord, in the French language channel, by user "Patubzh29"

**Comment by zeus86** [comment]
same here. delegating a stake works, but all staking-commands ultimatively fail with this error messages. 
(arch x86_64 with python venv. bittensor=6.6.0, python=3.11.6)

**Comment by ifrit98** [comment]
Fixed as of 6.6.1
