### ISSUE TITLE
Error when encrypting hotkey

### ISSUE THREAD

**Issue by buidles** [camfairchild/bittensor#1653]
### Describe the bug

Following instructions [here](https://docs.bittensor.com/getting-started/wallets#encrypting-the-hotkey) when trying to encrypt the hotkey I get the error:

```
Error: argument command: invalid choice: 'new_hotkey' (choose from 'subnets', 's', 'subnet', 'root', 'r', 'roots', 'wallet', 'w', 'wallets', 'stake', 'st', 'stakes', 'sudo', 'su', 'sudos', 'legacy', 'l', 'info', 'i')
```

### To Reproduce

1. Create hotkey as per documentation
2. Run `btcli new_hotkey --use_password`

### Expected behavior

Not to get error.

### Environment

MacOS 14.1, Bittensor 6.6.0

**Comment by ifrit98** [comment]
This is an error in documentation, nice catch! We will update this in the next release

here is the correct usage:
`btcli wallet new_hotkey` 

Bittensor's `btcli` uses `subcommands`.
