### ISSUE TITLE
Cannot claim senate seat

### ISSUE THREAD

**Issue by frankrizz07** [camfairchild/bittensor#1660]
### Describe the bug

I cannot claim a senate seat.  I am registered on root network, am nominated as a delegate to stake to (verified validator), and registered on subnetworks. (all requirements met)
When i do a btcli root list, I have a "No' listed in the Senator list. 

### To Reproduce

btcli root list
Address: 5CXRfP2ekFhe62r7q3vppRajJmGhTi7vwvb2yr79jveZ282w
UID: 5
Name: Rizzo

### Expected behavior

I should be promoted above the number 11 & 12 seats that DO NOT even meet the 2% criteria. thank you for your help in this matter. -Rizzo

### Environment

Ubuntu 6.6.0

**Comment by camfairchild** [comment]
The Senate should be adjusted during the next root epoch

Please close if you no longer have this issue

**Comment by frankrizz07** [comment]
Who's better than you, Cameron!?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by frankrizz07** [comment]
I don't think the issue was resolved. Still don't have a senate seat. Unless I don't understand how long a root Epoch is? Pls advise

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
