### ISSUE TITLE
Need to be able to dereg a uid or ip from a subnet as a validator. 

### ISSUE THREAD

**Issue by frankrizz07** [camfairchild/bittensor#1675]
### Describe the bug

people are running scripts on subnets to 'weight copy'.  this is not fair to 'real' validator operators who constantly have to keep up with changes on each subnet in an effort to be efficient and earn maximum emissions. Not to mention the monthly costs (capex/opex). Subnet owners and/or subnet validators need the ability to dereg these bad actors. 

### To Reproduce

look at any subnet

### Expected behavior

As a validator i have the ability to identify these 'weight copiers', but I can't do anything about it. What i am requesting is for Validators to have the ability to deregister these 'bad actors' from the subnet. 

This HUGE NETWORK PROBLEM has been an public for over 6 months! I think it's time that the foundation fix it or give the ability for us to fix it. Let's not continue to turn a blind eye (please and thank you)

### Environment

Ubuntu

**Comment by ifrit98** [comment]
This is not a bug with any specific code itself, but is a strategy that is employed by validators. 

If you have any specific suggestions, mitigations, or implementations, PRs are always welcome!
