### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by GaloisField2718** [camfairchild/bittensor#1709]
### Describe the bug

Hello,

I can't install `btcli` from `pip3 install bittensor` and from github install, on my ubuntu 22.04.4 LTS server

I have the error: 
```
error: subprocess-exited-with-error
  
  × Building wheel for ansible-vault (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [73 lines of output]
      /usr/lib/python3/dist-packages/setuptools/dist.py:723: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
[...]
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: install_layout. Did you mean: 'install_platlib'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for ansible-vault
Failed to build ansible-vault
ERROR: Could not build wheels for ansible-vault, which is required to install pyproject.toml-based projects
```

### To Reproduce

1. Login on my server
2. run `pip3 install bittensor`

Same for `git clone & python3 -m pip ...`

### Expected behavior

Install `btcli`.

### Environment

Ubuntu 22.04.4 LTS x86_64

### Additional context

Can I give any other information?

**Comment by GaloisField2718** [comment]
It's an issue with ansible_vault not you

**Comment by Abdullah7643** [comment]
@GaloisField2718 how did u resolved the issue with ansible_vault I am installing the complete package it shows that the successful but of ansible-vault but I am still having error: ModuleNotFoundError: No module named 'ansible.utils.vault'
