### ISSUE TITLE
Triple confirmation of stake add

### ISSUE THREAD

**Issue by ppolewicz** [camfairchild/bittensor#1713]
### Describe the bug

`btcli stake add` asks the user:
1. Do you want to stake to the following keys from owner: (...)
2. Enter password to unlock key:
3. Do you want to delegate:
  amount: (...)
  to: (...)
  take: 0.179995422293431
  owner: (...) [y/n]

### To Reproduce

add stake via cli

### Expected behavior

ideally we'd display the last message and ask for ctrl+C if the user disagrees or for the password if they do agree (if the key is encrypted) or just the final confirmation (if the key is not encrypted). Bothering users with unnecessary questions with long pauses between them is bad UX.

### Environment

linux

**Comment by thewhaleking** [comment]
Closed with 8.0.0
