### ISSUE TITLE
TooManyRegistrationsThisInterval

### ISSUE THREAD

**Issue by jacky68147527** [camfairchild/bittensor#1726]
### Describe the bug

❌ Failed: error:{'type': 'Module', 'name': 'TooManyRegistrationsThisInterval', 'docs': []}

### To Reproduce

btcli subnet register --netuid 1 --wallet.name xxxxx --wallet.hotkey xxxx

### Expected behavior

Tried multiple times, still failed

### Environment

ubuntu

**Comment by michaelkrasa** [comment]
This is regular behaviour. There is a limit on how many registrations can occur in the given window -- 3 regs every 72 minutes.
