### ISSUE TITLE
Fix Pysubstrate Websockets to Allow for Async Calls

### ISSUE THREAD

**Issue by garrett-opentensor** [camfairchild/bittensor#1736]
Description:  We have identified an issue in the Python Substrate Interface that causes interactions with the chain to hang when using multithreading in the Bittensor python API.  This is due to an issue surrounding this section of code which drops unexpected requests.  

https://github.com/polkascan/py-substrate-interface/blob/84485c1f7774016ed2f93380b3a6ec041c28b2c1/substrateinterface/base.py#L293

AC:
- [ ] Identify the correct method to correct the issue (submit PR to Pysubstrate repo, Fork, Override methods, etc)
- [ ] Fix the problem of dropped requests, to allow for asynchronous web socket connections

**Comment by thewhaleking** [comment]
Fixed with 8.0.0
