### ISSUE TITLE
Unable to register twice for same local subnet

### ISSUE THREAD

**Issue by Rubenduburck** [camfairchild/bittensor#1770]
### Describe the bug

Second registration to new subnet fails with 
```SubstrateRequestException: {'code': 1010, 'message': 'Invalid Transaction', 'data': 'Transaction would exhaust the block limits'}```

### To Reproduce

1. start localnet.sh
2. register two wallets
3. register new subnet
4. register wallet 1 with subnet
5. register wallet 2 with subnet
step 5 causes SubstrateRequestException: {'code' 1010, 'message':'Invalid Transaction', 'data': 'Transaction would exhaust the block limits'}

### Expected behavior

Registration as normal (works on branch `main`)

### Environment

Ubuntu 20.04, development branch

### Additional context

I have a Dockerfile that builds this repo from git, then deploys some wallets and registers a subnet, a miner and a validator. On more recent versions of this repo, this pipeline breaks at the validator registration step with the above mentioned error.

Tested also on two different machines.

**Comment by mjurbanski-reef** [comment]
Seems you need to adjust hyperparameters to be able to register in short succession
https://github.com/opentensor/bittensor/pull/1943/files/0115dfe1b32d5d98465a2f1aff882590357a9e70#r1615953975
