### ISSUE TITLE
Change github default branch to staging

### ISSUE THREAD

**Issue by mjurbanski-reef** [camfairchild/bittensor#1780]
### Is your feature request related to a problem? Please describe.

It is a common issue that PRs are branched from default branch (master) and then target master  ( https://github.com/opentensor/bittensor/pull/1749 , https://github.com/opentensor/bittensor/pull/1750, ...) despite CONTRIB instructions saying `staging` branch should be used.

An that is only natural, since it is different how most github project work, and is very easy to forget about it even if you did read Contributing instruction at the some point.

### Describe the solution you'd like

Change the default github branch to `staging`, which will make one less thing to remember for contributors and should not affect maintainers much. In fact they will also have less load on them since they will not have to correct contributors nearly as often.

IDK if people installing from source want to have bleeding-edge version or not, but if we assume they want stable then single adjustment to readme instruction has to be made after this change: `git clone -b master https://github.com/opentensor/bittensor.git`  .

### Describe alternatives you've considered

Just keep going as is, adding even more warning etc that only add cognitive load, but it seems like more confusion and work for everyone involved.

**Comment by rajkaramchedu** [comment]
From docs (docs.bittensor.com) point of view, this will work. I can modify the `git clone` instructions as @mjurbanski-reef suggested above.
