### ISSUE TITLE
"from websocket import create_connection, WebSocketConnectionClosedException" in BASE.PY - 29 line

### ISSUE THREAD

**Issue by LucasDcarprio** [camfairchild/bittensor#1804]
### Describe the bug

"from websocket import create_connection, WebSocketConnectionClosedException" in BASE.PY - 29 line

Too old of your codes its now use websockets or websocket-client 1.7.0 

and so many codes like this your codes is too old now , you should not defined all the modules , thats supid thing !!

### To Reproduce

BASE.PY
line 29 : from websocket import create_connection, WebSocketConnectionClosedException

btcli.py
line 27 : except websocket.WebSocketConnectionClosedException as e:

### Expected behavior

None

### Environment

Python 3.10

**Comment by thewhaleking** [comment]
This code is not in this repo, but rather in https://github.com/polkascan/py-substrate-interface
