### ISSUE TITLE
Add a parameter to select the uid range for `btcli root get_weights` command

### ISSUE THREAD

**Issue by gztensor** [camfairchild/bittensor#1930]
### Is your feature request related to a problem? Please describe.

On lower resolutions the result is poorly readable if the number of neurons is high:
<img width="1408" alt="image" src="https://github.com/opentensor/bittensor/assets/166415444/6dfb2742-94a8-4482-b4fd-c80827fb9a0f">

### Describe the solution you'd like

Please add the parameter (naming is discussable) that will allow to display only a range of uid colums, for example:
`--uid-range 5-13`

or two parameters (each is optional): 

```
--uid-range-start 5
--uid-range-stop 13
```

### Describe alternatives you've considered

It could be output to plain text instead of rich.table to allow arbitrary width so that output can be directed to a file, but range is probably easier to use and to implement.

**Comment by thewhaleking** [comment]
Fixed with 8.0.0
