### ISSUE TITLE
Increase the amount the faucet mints to at least 1k?

### ISSUE THREAD

**Issue by basfroman** [camfairchild/bittensor#1936]
### Is your feature request related to a problem? Please describe.

It comes from here 
 https://discord.com/channels/799672011265015819/1176889593136693339/1243454643569299477

### Describe the solution you'd like

Since creating a network (for test purposes) costs 1000, you have to do the “faucet” several times. This makes the testing process much more difficult.

There are 2 obvious solutions:

1. increase the amount the faucet mints to 1k
2. implement an additional parameter “--test” for the “faucet” command, which will return 1k faucet mints.

### Describe alternatives you've considered

Leave it as is and waste time during testing

**Comment by mjurbanski-reef** [comment]
3. Implement `--amount` so another flag does not need to be created if someone wants just 100 or needs 2k
