### ISSUE TITLE
btcli 6.12.2 hangs

### ISSUE THREAD

**Issue by Tegridy-X** [camfairchild/bittensor#1942]
### Describe the bug

There are several issues with bittensor 6.12.2 version:
1. Unable to perform btcli w overview
2. Unable to register btcli s register
3. Unable to remove stake btcli st remove

For example, running a while loop for wallet overview (with 40 hotkeys) is causing it to hang:

while true; do btcli w overview --subtensor.chain_endpoint 192.168.13.10:9944 --all; sleep 1800; done;

### To Reproduce

Create 2 coldkeys with 40 hotkeys in each. 

Run while loop with 900+ seconds delay, for example:

while true; do btcli w overview --subtensor.chain_endpoint 192.168.13.10:9944 --all; sleep 1800; done;

While this runs, try to register on a subnet.

### Expected behavior

Successful report of wallet overviews.

You should also be able to break-out of btcli with ctrl+c, yet this fails as the session hangs.

### Environment

Debian 12 / Bittensor 6.12.2

### Additional context

NOTE: 6.10.1 works well, rollback is a workaround

pip install bittensor==6.10.1

**Comment by Tegridy-X** [comment]
This is directly related to:
https://blog.bittensor.com/bittnesor-community-update-july-3-2024-45661b1d542d

I was 'pip installed' bittensor==6.12.2

**Comment by uncleluk21** [comment]
You where affacted?

**Comment by Tegridy-X** [comment]
> You where affacted?

100%
