### ISSUE TITLE
Internal vs External IP in Axon

### ISSUE THREAD

**Issue by opendansor** [camfairchild/bittensor#1965]
Rename `ip` to `internal_ip` add a comment saying so. 

On Axon.info return both `internal_ip` and `external_ip` (keep `ip` as it is, make a note for code-debt/deprecation later if needed)

This will help users clarify the difference in which ip they are looking at. 

Add tests to verify functionality.

**Comment by thewhaleking** [comment]
@opendansor is this issue resolved fully now?
