### ISSUE TITLE
Redesign user input/output for dtao

### ISSUE THREAD

**Issue by gztensor** [camfairchild/bittensor#2007]
The most critical screens: 

1. btcli root list
2. btcli stake delegate / undelegate
3. btcli subnets list
4. btcli st add / remove 
5. btcli r list_delegates
6. btcli st list
7. btcli w balance

Branch: `dynamic`

**Comment by edenbeamhost** [comment]
This seems to be implemented as we are polishing the dynamic branch :)

**Comment by thewhaleking** [comment]
> This seems to be implemented as we are polishing the dynamic branch :)

What do you mean?
