### ISSUE TITLE
Unable to retrieve subnet hyperparameters

### ISSUE THREAD

**Issue by Jackalgirl** [camfairchild/bittensor#2119]
### Describe the bug

`RemainingScaleBytesNotEmptyException: Decoding <SubnetHyperparameters> - Current offset: 83 / length: 92` returned when trying to retrieve subnet hyperparameters.  This happens on both testnet and mainnet.

### To Reproduce

Use: `btcli s hyperparameters --netuid 1`
Get a traceback that terminates with `RemainingScaleBytesNotEmptyException: Decoding <SubnetHyperparameters> - Current offset: 83 / length: 92`

### Expected behavior

Expected behavior: list of current hyperparameters for the requested netuid.

### Environment

Bittensor 7.3.0

**Comment by thewhaleking** [comment]
Closed by 8.0.0
