### ISSUE TITLE
reduce size of repo

### ISSUE THREAD

**Issue by samsammurphy** [camfairchild/bittensor#2124]
### Is your feature request related to a problem? Please describe.

I just cloned the repo and it is very large (329.54 Mi). 

For example we have been committing files that are up to 92Mb (uncompressed) which are up to 25 Mb (compressed). Do we definitely need these large files in the code base?

```
$ git verify-pack -v .git/objects/pack/pack-*.idx | sort -k 3 -n | tail -5
2a93756e8f04bbb8272ac61a163df2ef8b1b4f06 blob   73542832 25561023 3437204
e9a91973790e3176c45eed09b45b5e814ca775e6 blob   73557376 25568639 92121885
9934ecc0f68a18cefec3dd8a187e6aa1068a291a blob   79459952 21793270 189521843
068b413cbafc66920113f76976fce6c3fa064c04 blob   91905696 23011704 218439793
dd16a3a6811c3d8295451cb7d1d012de0091b312 blob   92356632 23089995 138420776
```

### Describe the solution you'd like

Can we find a way to reduce the size of the repo?

- Perhaps we could remove them with BFG Repo-Cleaner or git filter-branch?
- or if the file is necessary should we use Git LFS?

### Describe alternatives you've considered

I am not sure what the alternative is other than do nothing

### Additional context

I very large code base has a bad smell and may put off developers from contributing

**Comment by thewhaleking** [comment]
Hey @samsammurphy,
The actual codebase size is quite small (roughly 2MB), and has recently decreased substantially. However, it's still going to be around that 330MB mark in total size because of the way that git works. I'm not sure we would want to strip any part of the git history to save a bit of space.
