### ISSUE TITLE
Update Error Message for Nominate

### ISSUE THREAD

**Issue by thewhaleking** [camfairchild/bittensor#2160]
User getting error: 
```
Failed: Subtensor returned `HotKeyAccountNotExists (Module)` error. This means: `The hotkey does not exists`
```
when running `btcli r nominate  --subtensor.network=test` without first having registered to a network to have their hotkey associate.

```sh
btcli r nominate  --subtensor.network=test
Enter wallet name (default): 
Enter hotkey name (default): 
Enter password to unlock key: 
❌ Failed: error:Subtensor returned `HotKeyAccountNotExists (Module)` error. This means: `The hotkey does not exists`
Could not became a delegate on test
2024-07-23 16:37:37.393 |     WARNING      | Set weights -  - Failed: Subtensor returned `HotKeyAccountNotExists (Module)` error. This means: `The hotkey does not exists`
```

```python
bittensor.logging.warning(
    prefix="Set weights", suffix="<red>Failed: </red>" + str(e)
)
```
This message is coming from delegation.py nominate_extrinsic function.

Discord: https://discord.com/channels/799672011265015819/1265285303334076457/1265285303334076457

**Comment by basfroman** [comment]
I have implemented [formatter function](https://github.com/opentensor/bittensor/blob/master/bittensor/utils/__init__.py#L263) for subtensor errors. It should be used the same way as [here](https://github.com/opentensor/bittensor/blob/efa62398414454961386734ebe606d986274318d/bittensor/extrinsics/network.py#L117).

**Comment by thewhaleking** [comment]
> I have implemented [formatter function](https://github.com/opentensor/bittensor/blob/master/bittensor/utils/__init__.py#L263) for subtensor errors. It should be used the same way as [here](https://github.com/opentensor/bittensor/blob/efa62398414454961386734ebe606d986274318d/bittensor/extrinsics/network.py#L117).

This appears to already be using that function. The issue is with the message itself.

**Comment by basfroman** [comment]
> > I have implemented [formatter function](https://github.com/opentensor/bittensor/blob/master/bittensor/utils/__init__.py#L263) for subtensor errors. It should be used the same way as [here](https://github.com/opentensor/bittensor/blob/efa62398414454961386734ebe606d986274318d/bittensor/extrinsics/network.py#L117).
> 
> This appears to already be using that function. The issue is with the message itself.

Yeah, yeah, you're right. I missed this and confused it with another topic. But the name of the card is a little confusing. nvm

**Comment by ibraheem-abe** [comment]
Proposed error message - this is done by checking the participation of the neuron in any network before making the nomination call

![Image](https://github.com/user-attachments/assets/8b73585c-7b12-473e-98d7-4d4aad7154c6)
