### ISSUE TITLE
Minimal Local Subnet Demo Request

### ISSUE THREAD

**Issue by jingcheng407** [camfairchild/bittensor#2187]
I'm a beginner and I want to add and test my own local subnet. I've read the documentation and the code, but I still don't understand. It's a bit too complicated for me.
I would like a minimal demo project with the following functionality: 
the miner receives two integers, performs addition, and then sends the result out. The validator will verify the correctness of the result. 
I'm not sure if this constitutes a complete subnet project, so if it isn't, please let me know what other modules are missing.

**Comment by ibraheem-abe** [comment]
@jingcheng407 You can take a look at the subnet template repo: 

https://github.com/opentensor/bittensor-subnet-template/blob/for-staging-async-only-do-not-use-for-cloning/docs/running_on_staging.md

The miner does multiplication for the work and validators verify the correctness.
