### ISSUE TITLE
numpy version requirement while bittensor==8.0

### ISSUE THREAD

**Issue by wjurkowlaniec** [camfairchild/bittensor#2334]
### Describe the bug

When I want to have newest version of bittensor and tensorflow, I have clash of numpy requirement.

I can't have both installed in one project

### To Reproduce

```
pip install tensorflow==2.17.0 bittensor==8.0

ERROR: Cannot install bittensor==8.0.0 and tensorflow==2.17.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflow 2.17.0 depends on numpy<2.0.0 and >=1.26.0; python_version >= "3.12"
    bittensor 8.0.0 depends on numpy~=2.0.1
```

### Expected behavior

I should be able to install both.

I would suggest to lower version of numpy requirement, to at most 2.0.0

### Environment

OSX / Ubuntu

**Comment by thewhaleking** [comment]
Unfortunately, 2.0.0 would still not be compatible with tensorflow 2.17.0 (`tensorflow 2.17.0 depends on numpy<2.0.0 and >=1.26.0;`)

[Tensorflow 2.18.0rc0](https://pypi.org/project/tensorflow/2.18.0rc0/): `Requires-Dist: numpy <2.1.0,>=1.26.0`
It is currently in rc0, which was released 30 September. Their typical [release cadence](https://pypi.org/project/tensorflow/2.18.0rc0/#history) is two weeks after rc0, so you've got roughly a week left until that happens. 

I don't particularly want to go under numpy 2.0.1 for this, as it may require a bit of refactoring that would likely last roughly the same time as it takes for tensorflow 2.18.0 to fully release.
