### ISSUE TITLE
[SDK] Changing the external IP address of Axon if it is outside the proxy

### ISSUE THREAD

**Issue by basfroman** [camfairchild/bittensor#2429]
Issue came from here https://discord.com/channels/799672011265015819/1307912159828643910/1308062422069936189

**Comment by zyzniewski-reef** [comment]
I've tried with setting `BT_AXON_EXTERNAL_IP` env var and the provided address was successfully registered in metagraph (at least in testnet)

**Comment by basfroman** [comment]
Fixed
