### ISSUE TITLE
Client Colab Notebook Error

### ISSUE THREAD

**Issue by ms337** [camfairchild/bittensor#539]
**Describe the bug**
The Client Colab notebook linked on the readme does not work. Missing an import. 

**To Reproduce**
1. Click on the Open in Colab notebook in Section 3.1 in the README. 
2. Run all cells: first run the` ! pip install bittensor` cell. Then run the second cell. 
3. On running the second cell, we get the error: `ModuleNotFoundError: No module named 'scalecodec.block'`

**Expected behavior**
The notebook cell should run without error. 

**Screenshots**

<img width="939" alt="Screen Shot 2021-10-15 at 1 02 58 AM" src="https://user-images.githubusercontent.com/40411950/137434970-475688de-a09e-4b26-9af5-f0792417997d.png">

**Environment:**
 - Google Colab
 - Latest version of BitTensor as per the issue date. 

**Additional context**
Tried ` !pip install scalecodec` in the first cell. Issue persists.

**Comment by shibshib** [comment]
Thanks @ms337 ! @ndubuisx will take a look at this.

**Comment by ndubuisx** [comment]
Thanks for pointing this out @ms337! This problem has been resolve with the recent release: https://pypi.org/project/bittensor/1.7.4/
