### ISSUE TITLE
Smart Contracts

### ISSUE THREAD

**Issue by quac88** [camfairchild/bittensor#665]
Make smart contracts available to tao holders. Currently there is no trustless system to exchange tao. In addition, there is no trustless system for people to pool their tao together into a validator.

**Comment by liaopeiyuan** [comment]
^^^ especially enabling something like [Cross-Consensus Message Format (XCM)](https://wiki.polkadot.network/docs/learn-crosschain) could allow tao holders to provide liquidity on KSM/DOT parachains.
