### ISSUE TITLE
Change default action so that it does not automatically attempt to re-register hotkeys

### ISSUE THREAD

**Issue by hueymahl** [camfairchild/bittensor#804]
Currently when a hotkey is deregistered, bittensor starts a re-registration process for that hotkey by default.  The problem with this is that if you are running multiple miners on the same hardware, the stress of the re-registration attempt will max out the machine's resources and negatively impact the performance of the other miners.  This, in-turn, can lead to a cascade of hotkeys being deregistered.

I would prefer for the default action to be that the miner simply terminates and does not attempt to re-register when there is a deregistration event.  For those that wish to keep this feature, there can be a command that turns it on.

Alternatively, create a command to turn off auto-reregistration if the default action is left as-is.

Not re-registering was the default action previously.  If my memory serves, the justification for changing it was to make it easier to run a miner.  Then it made sense because the registration difficulty was negligible and did not negatively impact other running miners. That is no longer the case.

**Comment by joeylegere** [comment]
Closing this because the feature is done and will be merged into master as part of Synapse.
