### ISSUE TITLE
Minor grammar in Getting Started guide

### ISSUE THREAD

**Issue by thepinkturtle** [camfairchild/bittensor#842]
**Describe the bug**
Sorry folks I didn't know where to put this even after reading the docs on how to contribute. There's just a minor grammatical issue in the [Getting Started Guide](https://opentensor.gitbook.io/bittensor/tutorials%20/how-to-mine-tao#installation)

**To Reproduce**
1. Go to [Getting Started Guide](https://opentensor.gitbook.io/bittensor/tutorials%20/how-to-mine-tao#installation)
2. Read step '
To begin, paste this script into your macOS Terminal or Linus shell prompt: '
3. 'Linus' should be 'Linux'

**Expected behavior**
Correct Linus to Linux

**Screenshots**
![linus](https://user-images.githubusercontent.com/1828307/179084959-6633511b-73ee-4528-861f-cc8ee9be2f04.png)

**Environment:**
N/A

**Additional context**
N/A

**Comment by camfairchild** [comment]
This has since been correct. Thanks for the issue.
In future, you can suggest edits to the docs using the button in the top right 
![image](https://user-images.githubusercontent.com/24501463/180302445-6ace104e-9877-497b-86b4-9979cd363fe0.png)
