### ISSUE TITLE
Can't generate cold wallet

### ISSUE THREAD

**Issue by leedsrising** [camfairchild/bittensor#902]
**Describe the bug**

When trying to create my first coldkey, I'm running into an error

leedsrising@Leedss-MBP .bittensor % btcli new_coldkey
Traceback (most recent call last):
  File "/opt/homebrew/bin/btcli", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/Users/leedsrising/.bittensor/bittensor/bin/btcli", line 3, in <module>
    import bittensor 
  File "/Users/leedsrising/.bittensor/bittensor/bittensor/__init__.py", line 87, in <module>
    import bittensor._proto.bittensor_pb2_grpc as grpc
  File "/Users/leedsrising/.bittensor/bittensor/bittensor/_proto/bittensor_pb2_grpc.py", line 3, in <module>
    import grpc
  File "/opt/homebrew/lib/python3.10/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/opt/homebrew/lib/python3.10/site-packages/grpc/_compression.py", line 15, in <module>
    from grpc._cython import cygrpc
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so, 0x0002): tried: '/opt/homebrew/lib/python3.10/site-packages/grpc/_cython/cygrpc.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/cygrpc.cpython-310-darwin.so' (no such file), '/usr/lib/cygrpc.cpython-310-darwin.so' (no such file)

**To Reproduce**
Running command ```btcli new_coldkey``` after first install of bittensor with ```/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/opentensor/bittensor/master/scripts/install.sh)"```

**Expected behavior**
Would expect creation of my coldkey without ane error

**Environment:**
 - OS and Distro: macos version 12.0
 - Bittensor Version: N/A

**Comment by unconst** [comment]
Seem the error is originating from the GRPC version on mac.  

Specifically here: 
from grpc._cython import cygrpc

And:
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

Likely caused by M1 mac. 

UDPATE:
It appears that the issue is related to python3.10.
https://groups.google.com/g/grpc-io/c/HLB9GIY6F1s

Try installing python3.9 and reinstalling from source.
