### ISSUE TITLE
Issue with cubit.pyx

### ISSUE THREAD

**Issue by juansolana** [camfairchild/bittensor#908]
I'm trying to run a miner following the [documentation](https://docs.bittensor.com/RunningAMiner.html). I have already created my coldkey and my hotkey, installed cuda and checked that is available through console, and also installed cubit as described and verified that I'm able to import it. But when I try to run `btcli run --cuda` to start registration, an error is thrown.

Note that no issue seems to be occurring when I just run `btcli run`.

The error:
`/home/jj/bittensor/bittensor/cubit.pyx:164 in cubit.solve_cuda 
 [Errno 2] No such file or directory:
'/home/jj/bittensor/bittensor/cubit.pyx' 
TypeError: an integer is required
⠸ Solving%    `

**Environment:**
 - Linux Ubuntu 18.04
 - Python 3.9bit
 - Bittensor Version pulled from master

**Comment by camfairchild** [comment]
I'll open you an issue in the cubit repo https://github.com/opentensor/cubit/issues/1
