### ISSUE TITLE
Wallet generation fails without internet connection

### ISSUE THREAD

**Issue by karlvance** [camfairchild/bittensor#973]
**Describe the bug**
Creating new wallet generates error if connection to the internet is not available.  This makes it impossible to generate an offline wallet via the normal methods.

**To Reproduce**
* Downloaded the software within a user account:
pip install --user bittensor
* Disconnect internet connection.
* Attempt to create a new wallet
btcli new_coldkey
**Expected behavior**
Creates new wallet via normal function.

**Environment:**
 - Linux cr 5.10.53-1-MANJARO X86_64 GNU/Linux
 - Bittensor Version
 Cloned repo at date of this post

**Error messages**
```
ConnectionError: HTTPSCOnnectionPool(host='pypi.org', port=443): max retries exceeded with url:
/pypi/bittensor/json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x...>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
```

I'm told this may be due to btcli attempting to do a version check and failing when the internet connection is unavailable

**Comment by camfairchild** [comment]
should be fixed in #970
