### ISSUE TITLE
Way to monitor the distribution of the loss in live server.

### ISSUE THREAD

**Issue by ALI7861111** [camfairchild/bittensor#975]
I am having difficulty deciding which models are performing best and worst. I need to monitor the loss distribution over a whole period of time,

I am unable to get the Loss variable without local and remote train disabled in the https://github.com/opentensor/bittensor/tree/master/bittensor/_neuron/text)/core_server/run.py

**Describe alternatives you've considered**
I want to know where the loss variable in the live server is located. I may save to inside a DB and plot distribution or monitor the loss distribution for comparison of live run of different models

![image](https://user-images.githubusercontent.com/57672011/200138018-43941fca-7eb1-45a3-be3b-9a8dab194a04.png)

**Comment by Inquinim** [comment]
I would also like to see this integrated. It's difficult to get a good picture of how well a model performs.

**Comment by ifrit98** [comment]
Stale.
